### PR TITLE
Escape special characters in pattern searching

### PR DESCRIPTION
**Pull request by dan0907**
@raven42 @Shane-XB-Qian 
This should resolve the bug #736

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Review by raven42 — APPROVED** [review]

**Comment by Shane-XB-Qian** [comment]
Actually I had no confidence on your change on #735 the ‘pattern’, and the ‘hl’ a bit too specific to a special case, looks...
As for this md link header tag issue, just a case, I will try later..

**Comment by alerque** [comment]
Thanks for the quick fix @dan0907.

@Shane-XB-Qian If there is something still the matter feel free to report it, or even better submit a superior alternative, PRs are welcome for anything you know how to improve upon.

**Comment by Shane-XB-Qian** [comment]
@alerque donot need to say this.. you're admin-ing this repo, should be awared tagbar is not only working for  one/two specific langs.. better to avoid 'magic chars(/numbers)'..
i supposed @dan0907 and/or @raven42 knew what i mean..

**Comment by Shane-XB-Qian** [comment]
@dan0907 @raven42 to this issue itself (md link header tag), i tried, looks fixed. thx.

**Pull request merged**
