### PR TITLE
feature: Add basic Crystal support

### LINKED ISSUE #517: Add support for Crystal

### PR DESCRIPTION
**Pull request by dammer**
The Crystal [~/.ctags](https://github.com/dammer/crystal-ctags) file is need to work.

Peek 2021-08-05 22-05

Fixes #517

### CODE REVIEW

**Review by alerque — APPROVED** [review]
This is looking alright to me.

By the way have you tried submitting the Crystal info upstream to Universal Ctags? They are usually pretty receptive to new language support.

**Comment by raven42** [comment]
Looks good to me... only question would be if the `stl` flag should be 1 for all of them. Something like the macros for example I wouldn't think we'd want `stl=1`.

**Comment by dammer** [comment]
Thanks Caleb
> By the way have you tried submitting the Crystal info upstream to Universal Ctags? They are usually pretty receptive to new language support.

Actually no, but I see requests for adding support. I will try to ask familiar C coders about write commit.

**Comment by dammer** [comment]
@raven42 
> Looks good to me... only question would be if the `stl` flag should be 1 for all of them. Something like the macros for example I wouldn't think we'd want `stl=1`.

I checkd, in Crystal macro seems as defs not as in C macro.

**Review by raven42 — APPROVED** [review]

**Pull request merged**
